version: '3'

services:
    postgres:
        image: postgres
        volumes:
          - postgres_data:/var/lib/postgresql/data
        environment:
          POSTGRES_DB: keycl0ak
          POSTGRES_USER: keycl0ak
          POSTGRES_PASSWORD: superpassword
        ports:
          - 5438:5438
    keycloak:
        image: quay.io/keycloak/keycloak:legacy
        command: 
          - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
        environment:
          DB_VENDOR: POSTGRES
          DB_ADDR: postgres
          DB_DATABASE: keycl0ak
          DB_USER: keycl0ak
          DB_PASSWORD: superpassword
          KEYCLOAK_USER: administrat0r
          KEYCLOAK_PASSWORD: superpassword
        ports:
          - 8080:8080
        depends_on:
          - postgres

volumes:
    postgres_data:
      driver: local