version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_postgresql # <<< This is the address, change it to your external db ip/domain
      #DB_PORT: 5432
      DB_DATABASE: keycl0ak
      DB_USER: superuser
      DB_SCHEMA: public
      DB_PASSWORD: superpassword
      KEYCLOAK_USER: superuser
      KEYCLOAK_PASSWORD: superpassword
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    ports:
      - 8100:8100
    command: ["-Djboss.http.port=8100"]
    networks:
      - hemenyanimdaNetwork
networks:
  hemenyanimdaNetwork:
    external: true
