version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8282
    command:
    - 'php'
    - '-S'
    - '[::]:8282'
    - '-t'
    - '/var/www/html'
    entrypoint:
    - 'entrypoint.sh'
    - 'docker-php-entrypoint'
    networks: 
      - hemenyanimdaNetwork
networks:
  hemenyanimdaNetwork:
    external: true
